### ISSUE TITLE
Consider using zydis instead of capstone

### ISSUE THREAD

**Issue by bugproof** [stevemk14ebr/PolyHook_2_0#10]
https://github.com/zyantific/zydis

Capstone has a very big size. It was used in x64dbg first and it was replaced with zydis.

**Comment by stevemk14ebr** [comment]
I won't be doing that work, i spent a significant amount of time upstreaming patches to capstone to support the functionality i needed here. If someone else wants to create a 'ZyDis' disassembler class such as i did for capstone: https://github.com/stevemk14ebr/PolyHook_2_0/blob/master/sources/CapstoneDisassembler.cpp then i would merge that work (if it passed all tests)

**Comment by athre0z** [comment]
We are previous game-hackers as well and originally wrote Zydis as a disassembler to assist our hooking lib (which we never got around to actually build, lol). I suspect you'd find pretty much anything you'll need built in. We provide detailed information on what bytes of the input correspond to what instruction "segments" out-of-the-box (I suspect this might be what you had to contrib into Capstone since I remember some guy on UC having issues with this a while ago). If something turns out to be missing, we'll be happy to help!

**Comment by stevemk14ebr** [comment]
There is a usable branch for zydis now. It passes all my tests. I'm going to keep it as a branch forever i think.

**Comment by stevemk14ebr** [comment]
zydis is now in master. Both capstone and zydis are stubbed out. It's up to the user which they want to use.

**Comment by athre0z** [comment]
Noice! This will probably also make it easier to maintain for you compared to having two branches requiring constant synchronization.

**Comment by stevemk14ebr** [comment]
@athre0z would you be able to resolve https://github.com/microsoft/vcpkg/pull/8426 so i can enable zydis on vcpkg.

**Comment by athre0z** [comment]
I already sank like two days trying to get this thing to build on all platforms, working around bugs and platform specific behavior in vcpkg with this PR and now that I found some constellation where everything appears to be working fine locally on all platforms, it's breaking in their CI in some weird way that I cannot reproduce locally, presumably because of some kind of caching issue. Anyways, I'll try to get it fixed soon(tm).

**Comment by stevemk14ebr** [comment]
Yea...cmake can be fun. I wish you luck

**Comment by athre0z** [comment]
It's merged!

**Comment by stevemk14ebr** [comment]
great! @xeropresence would you be interested in taking a look?
