### ISSUE TITLE
IP relative data operation

### ISSUE THREAD

**Issue by ArthurGiannotta** [stevemk14ebr/PolyHook_2_0#108]
What is the current alternative to the error **"Cannot fixup IP relative data operation, needed disp. beyond max disp range: "**?
I checked polyhook's "ADetour.cpp" and saw it is not yet ready to handle my target's pesky "lea r8,qword ptr ds:[rip + 0x603CF6]".

**Comment by stevemk14ebr** [comment]
Hello, unfortunately you have limited choices here. Your best bet is to try and ensure that the trampoline is allocated within +- 2GB. If this is true then the RIP + 0x603CF6 part of that opcode will be able to be adjusted within the correct range. The issue is that if this trampoline is too far, the instruction is no longer big enough to encode the correct offset, a whole new instruction would have to be used instead, which would be wider, and therefore affect other instruction relocations, which becomes a problem generally as fixing one instruction may break others. That is why polyhook does not handle this.

To ensure the trampoline is within range, you have control over the hook method using `setDetourScheme`. This is used here: https://github.com/stevemk14ebr/PolyHook_2_0/blob/da5cd57a08fdd3900bcd31dc832c9b3e81edd178/sources/x64Detour.cpp#L281. VALLOC2_FALLBACK_CODE_CAVE  should give you the best coverage on most platforms. 

If you find that none of these schemes is suitable, then unfortunately you will have to manually patch your target yourself, or you could ask polyhook to hook AFTER your target's bad instruction by passing it an offset pointer like this:
```
x64Detour(target + <offset_past_instruction>, ....)
```

Polyhook will now hook your target mid-way through, but you may need to carefully craft your hook callback using raw assembly to execute correctly since a C stub would expect to be called at the very start rather than mid way though.

**Comment by ArthurGiannotta** [comment]
Unfortunately, mid function hook wasn't an alternative in this specific case. I ended up nopping "lea r8,qword ptr ds:[rip + 0x603CF6]" before calling polyhook, then loading the correct address into r8 from inside the detoured function using a .masm.

**Comment by stevemk14ebr** [comment]
Glad you got it!
