### ISSUE TITLE
[Question, Help Wanted, Feature Request] Hooking a class member function

### ISSUE THREAD

**Issue by laper32** [stevemk14ebr/PolyHook_2_0#153]
This continues #142 

Again, this issue is left for further people who want to do similar works can used for referencing.

Indeed, we need to get this member class function pointer, but the problem is: How?

By searching libraries what I've used, I found that SourceHook handles VTable function hook/Member class function hook and works well.
And I found that they are using FastDelegate to implement it.

see FastDelegate's essay: https://www.codeproject.com/Articles/7150/Member-Function-Pointers-and-the-Fastest-Possible
FastDelegate itself: https://github.com/alliedmodders/metamod-source/blob/master/core/sourcehook/FastDelegate.h
see SourceHook's: https://github.com/alliedmodders/metamod-source/tree/master/core/sourcehook

Here's my experiment code:

```cpp
class MyClass
{
public:
	void Func()
	{
		std::cout << "Function output." << std::endl;
	}
};

uint64_t trampoline = 0;

std::unique_ptr<PLH::x86Detour> dtr;

fastdelegate::FastDelegate<void> dlg;

MyClass c;

decltype(auto) callback()
{
	std::cout << "Before call" << std::endl;
	auto ret = PLH::FnCast(reinterpret_cast<void*>(trampoline), &dlg);
	return ret;
}

int main()
{
	dlg = fastdelegate::MakeDelegate(&c, &MyClass::Func);
	dtr = std::make_unique<PLH::x86Detour>((uint64_t)&dlg, (uint64_t)callback, &trampoline);

	dtr->hook();
	c.Func();
	dtr->unHook();
}
```

This compiles successfully, but doesn't work. :/

**Comment by stevemk14ebr** [comment]
There is no safe and standardizes way to get a raw pointer to a member function pointer. This is why I do not support this. If you give a correct function virtual address (a raw pointer) to polyhook, it will hook it successfully. If your hook is not working,  that's because you're providing an incorrect address, which suggests fastdelegate is failing. 

For MSVC, use this: https://stackoverflow.com/questions/8121320/get-memory-address-of-member-function. That's a non standard extension and is what MS detours itself suggests to use for this. If you're using another compiler, you are on your own.

You need to use a debugger and figure out what's going wrong on your own.
