### ISSUE TITLE
Spoofing Ret address

### ISSUE THREAD

**Issue by soltrac** [stevemk14ebr/PolyHook_2_0#43]
Hi,

I really don't understand how the spoof of the return address is handled. I'm checking the unit test
https://github.com/stevemk14ebr/PolyHook_2_0/blob/master/UnitTests/TestDetourNoTDx86.cpp

and I've made a working example, but it is not working. Can you explain a little bit more how it is done? In my example, I've used the ILCallback as you use them on your example, but after that I'm not sure how the spoof is done.

Edit: My final interest is spoof the return address inside the image of the hooked function

**Comment by stevemk14ebr** [comment]
sorry that is an old test, i removed the ability to spoof return address. Only return _value_ spoofing is currently supported. This is due to how complicated the asmjit re-writing became, you can probably still find that code in the commit history, but no guarantees on how well it will work or if it is even correct.

**Comment by soltrac** [comment]
I checked it, but yes, it is not working, thank you anyway!
