### ISSUE TITLE
HWBreakPointHook doesn't work, but BreakPointHook does....

### ISSUE THREAD

**Issue by Stenlan** [stevemk14ebr/PolyHook_2_0#49]
I saw [an issue like this](https://github.com/stevemk14ebr/PolyHook_2_0/issues/42) before, but I seem to have the same issue. I use a very simple console application, that just prints a line with 1 extra character everytime... No threads or anything. Using a BreakPointHook, it works perfectly. Using HWBreakPointHook, not at all. Even though ->hook() returns true, it just doesn't get triggered... Is this a bug, or does something different need to be done when using HWBreakPointHook as opposed to BreakPointHook?

**Comment by stevemk14ebr** [comment]
you can find an example usage here: https://github.com/stevemk14ebr/PolyHook_2_0/blob/05c49ac647ad6642320d7a05410a5e5e205d9d28/UnitTests/TestHWBreakpointHook.cpp#L22

you also mist not run under a debugger. Can you verify again, and if it doesn't work, post your code.

**Comment by Stenlan** [comment]
Yes I verified that. 

.exe I'm injecting into (/Od and /Ob0 compiler flags, before you ask):

`#include <iostream>
#include <thread>


static std::string modstring(std::string inStr) {
	return inStr + "o";
}

void thread1() {
	std::string kutshit = "Y";
	while (true) {
		std::cout << kutshit;
		std::cin.ignore(1000000, 'd');
		kutshit = std::string(modstring(kutshit));
	}
}

int main()
{
	thread1();
}`

.dll I'm injecting:

`#include "pch.h"

const uintptr_t injectionPracticeBase = (uintptr_t)GetModuleHandleW(L"injectionpractice.exe");

uint64_t modString = injectionPracticeBase + 0x1480; // change this to whatever value it becomes when compiled

uint64_t modStringOrig = NULL;

std::shared_ptr<PLH::BreakPointHook> bpHook;

NOINLINE std::string modStringDetour() {
    auto protObj = bpHook->getProtectionObject();
    return "test";
}

void tmain() {
	std::cout << std::string("hooked") << std::endl;

	bpHook = std::make_shared<PLH::BreakPointHook>((uint64_t)modString, (uint64_t)modStringDetour);

	std::cout << (bpHook->hook() ? "yes" : "no") << std::endl;
}

BOOL APIENTRY DllMain( HMODULE hModule,
                       DWORD  ul_reason_for_call,
                       LPVOID lpReserved
                     )
{
    switch (ul_reason_for_call)
    {
    case DLL_PROCESS_ATTACH:
		DisableThreadLibraryCalls(hModule);
		CreateThread(NULL, 0, (LPTHREAD_START_ROUTINE)tmain, NULL, 0, NULL); // before you ask, I also tried executing tmain without createthread, doesn't work either
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}`

**Comment by Stenlan** [comment]
That is the BreakPointHook, obviously, which works, but using HWBreakPointHook it doesn't.

**Comment by stevemk14ebr** [comment]
ok, when I get time I'll look into this issue. I don't see any obvious errors in your code

**Comment by Stenlan** [comment]
Thank you, tell me if you need clarification

**Comment by stevemk14ebr** [comment]
Ok found the problem. Per design, the HWBP hook only hooks the function on the thread that calls hook(). The debug registers are local to the thread, and must be set per each thread. Regardless of you calling create thread in dll or main or not, you're likely on a different thread than the application due to how dll injectors work (virtualalloc + create remote thread usually). To fix this you need to call hook from the context of the thread. You can hook with another type first and setup your hwbp inside that handler, or you can modify polyhook to enumerate threads and hook each of them instead of just GetCurrentThread(). Just to prove it to yourself you can place the line:

`printf("thread id: %X", GetThreadId(GetCurrentThread()));`

in both your dll function where you call hook, and the loop inside your target. Also!!! Your function typdef must match: 

```
NOINLINE std::string modStringDetour() {
    auto protObj = bpHook->getProtectionObject();
    return "test";
}
```
it's missing the std::string argument. Beware that allocating objects across dll boundaries is dangerous if the runtimes are not sharing a heap. https://stackoverflow.com/questions/35310117/debug-assertion-failed-expression-acrt-first-block-header

**Comment by Stenlan** [comment]
Hmm okay thank you, although the ThreadID I get from the DLL seems to be a garbage value. But that has nothing to do with PolyHook. Thanks for your answer
